In [24]:
# import liabraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import xgboost as xgb
from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [7]:
# loading the dataset
df= pd.read_csv('NSE_SCOM_Safaricom.csv')
df.head()

         Date  Open  High   Low  Close    Vol. Change %
0  11-06-2012  3.40  3.45  3.35   3.40   3.24M    0.00%
1  12-06-2012  3.40  3.50  3.40   3.45   6.09M    1.47%
2  13-06-2012  3.45  3.45  3.35   3.40   7.29M   -1.45%
3  14-06-2012  3.40  3.45  3.35   3.40  31.81M    0.00%
4  15-06-2012  3.40  3.50  3.40   3.40   7.57M    0.00%

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1753 entries, 0 to 1752
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1753 non-null   object
 1   Open      1753 non-null   float64
 2   High      1753 non-null   float64
 3   Low       1753 non-null   float64
 4   Close     1753 non-null   float64
 5   Vol.      1753 non-null   object
 6   Change %  1753 non-null   object
dtypes: float64(4), object(3)
memory usage: 96.0+ KB

In [9]:
df.describe()

              Open         High          Low        Close
count  1753.000000  1753.000000  1753.000000  1753.000000
mean     16.797233    17.045807    16.591671    16.783434
std       7.694943     7.776212     7.568492     7.637384
min       0.000000     3.450000     3.350000     3.400000
25%      12.000000    12.100000    11.900000    12.000000
50%      16.250000    16.500000    16.050000    16.250000
75%      23.500000    23.750000    23.050000    23.450000
max      32.750000    33.500000    32.500000    32.750000

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()/len(df)*100

Date        0.0
Open        0.0
High        0.0
Low         0.0
Close       0.0
Vol.        0.0
Change %    0.0
dtype: float64

In [12]:
df['Change %'] = df['Change %'].str.replace('%', '')
df['Change %'] = df['Change %'].astype(float)

In [16]:
def clean_volume(x):
    
    if 'M' in str(x):
        return float(x.replace('M', '')) * 1_000_000
    
    elif 'K' in str(x):
        return float(x.replace('K', '')) * 1_000
    
    else:
        return float(x)

# Apply function
df['Vol.'] = df['Vol.'].apply(clean_volume)

In [17]:
df.head()

         Date  Open  High   Low  Close   Vol.  Change %
0  11-06-2012  3.40  3.45  3.35   3.40   3.24      0.00
1  12-06-2012  3.40  3.50  3.40   3.45   6.09      1.47
2  13-06-2012  3.45  3.45  3.35   3.40   7.29     -1.45
3  14-06-2012  3.40  3.45  3.35   3.40  31.81      0.00
4  15-06-2012  3.40  3.50  3.40   3.40   7.57      0.00

In [19]:
y = df['Close']
x = df.drop(['Close', 'Date'], axis=1)

## training the model

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Modeling

## linerRegression

In [21]:
log_reg = LinearRegression()
log_reg.fit(x_train, y_train)
log_pred = log_reg.predict(x_test)

mse_log = mean_squared_error(y_test, log_pred)  
r2_log = r2_score(y_test, log_pred)

print(f"Linear Regression MSE: {mse_log}")
print(f"Linear Regression R²: {r2_log}")

Linear Regression MSE: 0.017050061324292057
Linear Regression R²: 0.99970095081493

## Random forest regression

In [22]:
rf_reg = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg.fit(x_train, y_train)
rf_pred = rf_reg.predict(x_test)

mse_rf = mean_squared_error(y_test, rf_pred)
r2_rf = r2_score(y_test, rf_pred)

print(f"Random Forest MSE: {mse_rf}")
print(f"Random Forest R²: {r2_rf}")

Random Forest MSE: 0.02452753603988615
Random Forest R²: 0.9995697998074616

## xGboost

In [25]:
x_gb_reg = xgb.XGBRegressor(n_estimators=100, random_state=42)
x_gb_reg.fit(x_train, y_train)
x_gb_pred = x_gb_reg.predict(x_test)

mse_xgb = mean_squared_error(y_test, x_gb_pred)
r2_xgb = r2_score(y_test, x_gb_pred)

print(f"XGBoost MSE: {mse_xgb}")
print(f"XGBoost R²: {r2_xgb}")

XGBoost MSE: 0.04162950199154884
XGBoost R²: 0.9992698402422927